/** Códigos canónicos devueltos por GET /api/v1/auth/me. */
export const PERMISSIONS = {
  DASHBOARD_VIEW: 'REPORTES_DIARIOS_CONSULTAR',
  STUDENTS_VIEW: 'ALUMNOS_CONSULTAR',
  STUDENTS_DETAIL: 'ALUMNOS_CONSULTAR',
  STUDENTS_CREATE: 'ALUMNOS_CREAR',
  STUDENTS_EDIT: 'ALUMNOS_MODIFICAR',
  STUDENTS_DEACTIVATE: 'ALUMNOS_DESACTIVAR',
  PLANS_VIEW: 'PLANES_CONSULTAR',
  PLANS_CREATE: 'PLANES_GESTIONAR',
  PLANS_EDIT: 'PLANES_GESTIONAR',
  MEMBERSHIPS_VIEW: 'MEMBRESIAS_CONSULTAR',
  MEMBERSHIPS_CREATE: 'MEMBRESIAS_CREAR',
  MEMBERSHIPS_RENEW: 'MEMBRESIAS_MODIFICAR',
  /** payments.read; alias VIEW conservado por compatibilidad con Sprint 0. */
  PAYMENTS_READ: 'PAGOS_CONSULTAR',
  PAYMENTS_VIEW: 'PAGOS_CONSULTAR',
  PAYMENTS_DETAIL: 'PAGOS_CONSULTAR',
  PAYMENTS_RECEIPT: 'PAGOS_CONSULTAR',
  PAYMENTS_REGISTER: 'PAGOS_REGISTRAR',
  /** cash.read; alias VIEW conservado por compatibilidad con Sprint 0. */
  CASH_READ: 'CAJA_CONSULTAR',
  CASH_VIEW: 'CAJA_CONSULTAR',
  CASH_OPEN: 'CAJA_ABRIR',
  CASH_CLOSE: 'CAJA_CERRAR',
  ATTENDANCE_VIEW: 'ASISTENCIAS_CONSULTAR',
  ATTENDANCE_REGISTER: 'ASISTENCIAS_REGISTRAR',
  REPORTS_VIEW: 'REPORTES_DIARIOS_CONSULTAR',
  SECURITY_VIEW: 'USUARIOS_CONSULTAR',
  /** Reservado para Fase 3; aún no figura en el contrato recibido. */
  SPORTS_VIEW: 'DEPORTIVO_CONSULTAR',
} as const;
